spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proEx2?serverTimezone=UTC
    username: root
    password: abcd0123
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
server:
  port: 80
